// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'my_app.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: '/home/tab_other',
    uri: Uri.parse('/home/tab_other'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(key: '/home', uri: Uri.parse('/home'), routeBuilder: b1Builder),
  RouteEntity(
    key: '/home/tab_counter',
    uri: Uri.parse('/home/tab_counter'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: '/config',
    uri: Uri.parse('/config'),
    routeBuilder: b3Builder,
  ),
];

const routePaths = (
  path: '/',
  home: (
    path: '/home',
    tabOther: '/home/tab_other',
    tabCounter: '/home/tab_counter',
  ),
  config: '/config',
);
